###服务启动端口号
server:
  port: 8300
###服务名称(服务注册到eureka名称)
spring:
  application:
    name: app-nbkj-member
###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka

####swagger相关配置
swagger:
  base-package: com.nbkj.member.service
  title: 诺铂科技平台-会员服务接口
  description: 该项目是诺铂科技核心内部项目，未经允许，不得传播。
  version: 1.0
  terms-of-service-url: www.nbkj.com.cn
  contact:
    name: BingShu
    email: 1058179540@qq.com